name: "Test Workflow"

on:
  push:
    branches:
      - main

jobs:
  explore-repo:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v6.1.0
      - name: "Where Am I?"
        run: pwd
      - name: "List all files in tree"
        run: tree -a
